name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t devops-node-app .
          docker tag devops-node-app:latest 359642224114.dkr.ecr.us-east-1.amazonaws.com/devops-node-app:latest
          docker push 359642224114.dkr.ecr.us-east-1.amazonaws.com/devops-node-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 359642224114.dkr.ecr.us-east-1.amazonaws.com
            docker pull 359642224114.dkr.ecr.us-east-1.amazonaws.com/devops-node-app:latest
            docker stop devops-app || true
            docker rm devops-app || true
            docker run -d --name devops-app -p 80:3000 359642224114.dkr.ecr.us-east-1.amazonaws.com/devops-node-app:latest
